### ISSUE TITLE
Is there a URL scheme that can be used to open a specific station in the app?

### ISSUE THREAD

**Issue by ajmarkow** [StarPlayrX/StarPlayrX_iOS#3]
I would love if there was a url scheme so I can deeplink to a specific channel from ios shortcuts. Is there a way to do so with the app?

**Comment by macOS26** [comment]
No but I think StarPlayr would need auto play added to make this useful. Right now there is no mechanism to tell StarPlayr to play anything. I’m thinking about overhauling the UI soon in favor of SwiftUI. This is one of my only apps that still uses UIKit. Then changes like these would be easier.Sent from my iPhoneOn Oct 22, 2023, at 10:50 PM, AJ Markow ***@***.***> wrote:﻿
I would love if there was a url scheme so I can deeplink to a specific channel from ios shortcuts. Is there a way to do so with the app?

**Comment by ajmarkow** [comment]
Thanks!
